### PR TITLE
Add timing parameter

### PR DESCRIPTION
**Pull request by tchak**

### CODE REVIEW

**Comment by knownasilya** [comment]
Any chance this could get merged?

**Comment by mixonic** [comment]
@knownasilya two thoughts:

* Would an options object be more flexible? Why only `timing`?
* We need to document this if we add it.

**Comment by knownasilya** [comment]
I'd be 👍 on an options object, so it's obvious what it does and can expand with new options.

**Comment by knownasilya** [comment]
@tchak can you do that, or should I submit a new PR?

**Pull request closed without merging**
